### ISSUE TITLE
Cant run the website!

### ISSUE THREAD

**Issue by RayyanRS6** [danutama/reactjs-movie#1]
im unable to run it
i have my own api

where to put it?

im newbie

**Comment by danutama** [comment]
If you're having trouble running the project and you have your own ```API```, here’s a general guide on how to set things up:

Install Dependencies:
If the project has both a ```client``` (React frontend) and a ```server``` (backend), you will need to install dependencies in both folders.

First, navigate to the ```client``` folder and install dependencies:

`cd client`
`pnpm install`

Then, if there’s a ```server``` folder, install the dependencies there as well:

`cd ../server`
`pnpm install`

Add your API:
If the project has a backend (```server```), you may need to configure your API in the ```server``` folder. Look for a ```.env``` file or an example file like ```.env.example``` in the ```server``` folder, where you can put your API credentials or base URL.

Running the Project:
After installing dependencies and setting up your API, you can run the frontend and backend. To run the client (React app):

`cd client`
`pnpm run dev`

To run the server (if applicable):

`cd ../server`
`node index`

**Comment by danutama** [comment]
If you're having trouble running the project and you have your own ```API```, here’s a general guide on how to set things up:

**Install Dependencies:**
If the project has both a ```client``` (frontend) and a ```server``` (backend), you will need to install dependencies in both folders.

First, navigate to the ```client``` folder and install dependencies:

`cd client`
`pnpm install`

Then, if there’s a ```server``` folder, install the dependencies there as well:

`cd server`
`pnpm install`

**Add your API:**
If the project has a backend (```server```), you may need to configure your API in the ```server``` folder. Create ```.env``` file, add this: `TMDB_API_KEY=your_api_key`


**Running Project:**
After installing dependencies and setting up your API, you can run the frontend and backend. To run the client:

`cd client`
`pnpm run dev`

To run the server:

`cd server`
`pnpm start`
